# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UnityBuildTask@3
  inputs:
    buildTarget: 'Android'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'pong'
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: 
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'pong'
    publishLocation: 'Container'
